export const FETCH_JOURNALS_REQUEST = 'FETCH_JOURNALS_REQUEST'
export const FETCH_JOURNALS_SUCCESS = 'FETCH_JOURNALS_SUCCESS'
export const FETCH_JOURNALS_FAILURE = 'FETCH_USER_FAILURE'

export const POST_JOURNAL_REQUEST = 'POST_JOURNAL_REQUEST'
export const POST_JOURNAL_SUCCESS = 'POST_JOURNAL_SUCCESS'
export const POST_JOURNAL_FAILURE = 'POST_JOURNAL_FAILURE'